### ISSUE TITLE
where is data_process.py

### ISSUE THREAD

**Issue by Messiz** [Disguiser15/RefTeacher#1]
I'm very interesting in your work, but I have some trouble when I try to run it. I can't find data_process.py in data directory, could you please upload the py file? Thanks!

**Comment by Disguiser15** [comment]
Thank you for your interest! You can find data_processing.py in this url (https://github.com/luogen1996/SimREC/tree/main/data). You can follow the project (https://github.com/luogen1996/SimREC) to do data processing.

**Comment by Messiz** [comment]
Thank you so much for your quick reply！
